### PR TITLE
Utilize map to store listeners instead of slice, enhancing performance

### PR DESCRIPTION
**Pull request by panjf2000**
Code changes had been tested locally, including unit-test and benchmark-test.

### CODE REVIEW

**Comment by tidwall** [comment]
I appreciate your interest in contributing to evio, but unfortunately, this PR has too many changes to merge. As it stands, I can't exactly tell what's being fixed. Or, is it primary performance enhancements?

**Comment by panjf2000** [comment]
Maybe you can learn the intention of each code change from the commit message?

**Comment by panjf2000** [comment]
@tidwall 
At the beginning, I intended to utilize map to store listeners instead of slice which I think it would have a better performance, when it comes to `Multiple addresses` in case of vast addresses in one loop, and then I made some other optimizations incidentally.😁

**Comment by panjf2000** [comment]
About the additional code changes in this PR, those are mainly about:
1. Make a more normalized structure in `evio` by moving methods which is belong to interface `listener` from `evio_unix.go` to `evio.go`, cuz in my point of view, `evio_unix.go` and `evio_std.go` should be independent from each other, I especially object to `evio_std.go` invoking `evio_unix.go`, that would be not recommended.
2. Use `sync.Once` to make sure it would only call `signalShutdow` once when trying to shutdown `evio` cuz I found that it would call this function as many times as the number of loops and listeners.
3. Simplify the interface `Conn`, I found the `addrIndex` field was redundant here cuz it was never used(yet?).

**Comment by panjf2000** [comment]
After I do the benchmark test between Slice and Map in seeking elements, it turns out Slice would beat Map under the small length of elements, so the prime intention of this PR would not stand anymore, I will close it and create a new one that just involves some additional changes of this PR, thanks!

**Pull request closed without merging**
